const pokemonData = [
  {
    id: 1,
    name: "Bulbasaur",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: "Ivysaur",
    evolution_requirement: { level: 16 },
    evolution_relation: { chain: "Bulbasaur -> Ivysaur -> Venusaur" },
    size: "small",
    egg_group: ["Monster", "Grass"],
    legendary: false,
  },
  {
    id: 2,
    name: "Ivysaur",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: "Venusaur",
    evolution_requirement: { level: 32 },
    evolution_relation: { chain: "Bulbasaur -> Ivysaur -> Venusaur" },
    size: "medium",
    egg_group: ["Monster", "Grass"],
    legendary: false,
  },
  {
    id: 3,
    name: "Venusaur",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Bulbasaur -> Ivysaur -> Venusaur" },
    size: "large",
    egg_group: ["Monster", "Grass"],
    legendary: false,
  },
  {
    id: 4,
    name: "Charmander",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: "Charmeleon",
    evolution_requirement: { level: 16 },
    evolution_relation: { chain: "Charmander -> Charmeleon -> Charizard" },
    size: "small",
    egg_group: ["Monster", "Dragon"],
    legendary: false,
  },
  {
    id: 5,
    name: "Charmeleon",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: "Charizard",
    evolution_requirement: { level: 36 },
    evolution_relation: { chain: "Charmander -> Charmeleon -> Charizard" },
    size: "medium",
    egg_group: ["Monster", "Dragon"],
    legendary: false,
  },
  {
    id: 6,
    name: "Charizard",
    type: ["Fire", "Flying"],
    counter_type: ["Electric", "Rock", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Charmander -> Charmeleon -> Charizard" },
    size: "medium",
    egg_group: ["Monster", "Dragon"],
    legendary: false,
  },
  {
    id: 7,
    name: "Squirtle",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Wartortle",
    evolution_requirement: { level: 16 },
    evolution_relation: { chain: "Squirtle -> Wartortle -> Blastoise" },
    size: "small",
    egg_group: ["Monster", "Water 1"],
    legendary: false,
  },
  {
    id: 8,
    name: "Wartortle",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Blastoise",
    evolution_requirement: { level: 36 },
    evolution_relation: { chain: "Squirtle -> Wartortle -> Blastoise" },
    size: "medium",
    egg_group: ["Monster", "Water 1"],
    legendary: false,
  },
  {
    id: 9,
    name: "Blastoise",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Squirtle -> Wartortle -> Blastoise" },
    size: "medium",
    egg_group: ["Monster", "Water 1"],
    legendary: false,
  },
  {
    id: 10,
    name: "Caterpie",
    type: ["Bug"],
    counter_type: ["Fire", "Flying", "Rock"],
    evolution: "Metapod",
    evolution_requirement: { level: 7 },
    evolution_relation: { chain: "Caterpie -> Metapod -> Butterfree" },
    size: "extra_small",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 11,
    name: "Metapod",
    type: ["Bug"],
    counter_type: ["Fire", "Flying", "Rock"],
    evolution: "Butterfree",
    evolution_requirement: { level: 10 },
    evolution_relation: { chain: "Caterpie -> Metapod -> Butterfree" },
    size: "small",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 12,
    name: "Butterfree",
    type: ["Bug", "Flying"],
    counter_type: ["Electric", "Fire", "Flying", "Ice", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Caterpie -> Metapod -> Butterfree" },
    size: "medium",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 13,
    name: "Weedle",
    type: ["Bug", "Poison"],
    counter_type: ["Fire", "Flying", "Psychic", "Rock"],
    evolution: "Kakuna",
    evolution_requirement: { level: 7 },
    evolution_relation: { chain: "Weedle -> Kakuna -> Beedrill" },
    size: "extra_small",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 14,
    name: "Kakuna",
    type: ["Bug", "Poison"],
    counter_type: ["Fire", "Flying", "Psychic", "Rock"],
    evolution: "Beedrill",
    evolution_requirement: { level: 10 },
    evolution_relation: { chain: "Weedle -> Kakuna -> Beedrill" },
    size: "small",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 15,
    name: "Beedrill",
    type: ["Bug", "Poison"],
    counter_type: ["Fire", "Flying", "Psychic", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Weedle -> Kakuna -> Beedrill" },
    size: "small",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 16,
    name: "Pidgey",
    type: ["Normal", "Flying"],
    counter_type: ["Electric", "Ice", "Rock"],
    evolution: "Pidgeotto",
    evolution_requirement: { level: 18 },
    evolution_relation: { chain: "Pidgey -> Pidgeotto -> Pidgeot" },
    size: "extra_small",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 17,
    name: "Pidgeotto",
    type: ["Normal", "Flying"],
    counter_type: ["Electric", "Ice", "Rock"],
    evolution: "Pidgeot",
    evolution_requirement: { level: 36 },
    evolution_relation: { chain: "Pidgey -> Pidgeotto -> Pidgeot" },
    size: "medium",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 18,
    name: "Pidgeot",
    type: ["Normal", "Flying"],
    counter_type: ["Electric", "Ice", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Pidgey -> Pidgeotto -> Pidgeot" },
    size: "medium",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 19,
    name: "Rattata",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: "Raticate",
    evolution_requirement: { level: 20 },
    evolution_relation: { chain: "Rattata -> Raticate" },
    size: "extra_small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 20,
    name: "Raticate",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Rattata -> Raticate" },
    size: "small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 21,
    name: "Spearow",
    type: ["Normal", "Flying"],
    counter_type: ["Electric", "Ice", "Rock"],
    evolution: "Fearow",
    evolution_requirement: { level: 20 },
    evolution_relation: { chain: "Spearow -> Fearow" },
    size: "extra_small",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 22,
    name: "Fearow",
    type: ["Normal", "Flying"],
    counter_type: ["Electric", "Ice", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Spearow -> Fearow" },
    size: "medium",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 23,
    name: "Ekans",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: "Arbok",
    evolution_requirement: { level: 22 },
    evolution_relation: { chain: "Ekans -> Arbok" },
    size: "large",
    egg_group: ["Field", "Dragon"],
    legendary: false,
  },
  {
    id: 24,
    name: "Arbok",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Ekans -> Arbok" },
    size: "large",
    egg_group: ["Field", "Dragon"],
    legendary: false,
  },
  {
    id: 25,
    name: "Pikachu",
    type: ["Electric"],
    counter_type: ["Ground"],
    evolution: "Raichu",
    evolution_requirement: { stone: "Thunder Stone" },
    evolution_relation: { chain: "Pikachu -> Raichu" },
    size: "extra_small",
    egg_group: ["Field", "Fairy"],
    legendary: false,
  },
  {
    id: 26,
    name: "Raichu",
    type: ["Electric"],
    counter_type: ["Ground"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Pikachu -> Raichu" },
    size: "small",
    egg_group: ["Field", "Fairy"],
    legendary: false,
  },
  {
    id: 27,
    name: "Sandshrew",
    type: ["Ground"],
    counter_type: ["Grass", "Ice", "Water"],
    evolution: "Sandslash",
    evolution_requirement: { level: 22 },
    evolution_relation: { chain: "Sandshrew -> Sandslash" },
    size: "small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 28,
    name: "Sandslash",
    type: ["Ground"],
    counter_type: ["Grass", "Ice", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Sandshrew -> Sandslash" },
    size: "medium",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 29,
    name: "Nidoran♀",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: "Nidorina",
    evolution_requirement: { level: 16 },
    evolution_relation: { chain: "Nidoran♀ -> Nidorina -> Nidoqueen" },
    size: "extra_small",
    egg_group: ["Field", "Monster"],
    legendary: false,
  },
  {
    id: 30,
    name: "Nidorina",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: "Nidoqueen",
    evolution_requirement: { stone: "Moon Stone" },
    evolution_relation: { chain: "Nidoran♀ -> Nidorina -> Nidoqueen" },
    size: "small",
    egg_group: ["Undiscovered"],
    legendary: false,
  },
  {
    id: 31,
    name: "Nidoqueen",
    type: ["Poison", "Ground"],
    counter_type: ["Ground", "Ice", "Psychic", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Nidoran♀ -> Nidorina -> Nidoqueen" },
    size: "medium",
    egg_group: ["Undiscovered"],
    legendary: false,
  },
  {
    id: 32,
    name: "Nidoran♂",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: "Nidorino",
    evolution_requirement: { level: 16 },
    evolution_relation: { chain: "Nidoran♂ -> Nidorino -> Nidoking" },
    size: "small",
    egg_group: ["Field", "Monster"],
    legendary: false,
  },
  {
    id: 33,
    name: "Nidorino",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: "Nidoking",
    evolution_requirement: { stone: "Moon Stone" },
    evolution_relation: { chain: "Nidoran♂ -> Nidorino -> Nidoking" },
    size: "small",
    egg_group: ["Field", "Monster"],
    legendary: false,
  },
  {
    id: 34,
    name: "Nidoking",
    type: ["Poison", "Ground"],
    counter_type: ["Ground", "Ice", "Psychic", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Nidoran♂ -> Nidorino -> Nidoking" },
    size: "medium",
    egg_group: ["Field", "Monster"],
    legendary: false,
  },
  {
    id: 35,
    name: "Clefairy",
    type: ["Fairy"],
    counter_type: ["Poison", "Steel"],
    evolution: "Clefable",
    evolution_requirement: { stone: "Moon Stone" },
    evolution_relation: { chain: "Clefairy -> Clefable" },
    size: "small",
    egg_group: ["Fairy"],
    legendary: false,
  },
  {
    id: 36,
    name: "Clefable",
    type: ["Fairy"],
    counter_type: ["Poison", "Steel"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Clefairy -> Clefable" },
    size: "medium",
    egg_group: ["Fairy"],
    legendary: false,
  },
  {
    id: 37,
    name: "Vulpix",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: "Ninetales",
    evolution_requirement: { stone: "Fire Stone" },
    evolution_relation: { chain: "Vulpix -> Ninetales" },
    size: "small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 38,
    name: "Ninetales",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Vulpix -> Ninetales" },
    size: "medium",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 39,
    name: "Jigglypuff",
    type: ["Normal", "Fairy"],
    counter_type: ["Poison", "Steel"],
    evolution: "Wigglytuff",
    evolution_requirement: { stone: "Moon Stone" },
    evolution_relation: { chain: "Jigglypuff -> Wigglytuff" },
    size: "small",
    egg_group: ["Fairy"],
    legendary: false,
  },
  {
    id: 40,
    name: "Wigglytuff",
    type: ["Normal", "Fairy"],
    counter_type: ["Poison", "Steel"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Jigglypuff -> Wigglytuff" },
    size: "medium",
    egg_group: ["Fairy"],
    legendary: false,
  },
  {
    id: 41,
    name: "Zubat",
    type: ["Poison", "Flying"],
    counter_type: ["Electric", "Psychic", "Rock"],
    evolution: "Golbat",
    evolution_requirement: { level: 22 },
    evolution_relation: { chain: "Zubat -> Golbat" },
    size: "small",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 42,
    name: "Golbat",
    type: ["Poison", "Flying"],
    counter_type: ["Electric", "Psychic", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Zubat -> Golbat" },
    size: "medium",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 43,
    name: "Oddish",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: "Gloom",
    evolution_requirement: { level: 21 },
    evolution_relation: { chain: "Oddish -> Gloom -> Vileplume" },
    size: "small",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 44,
    name: "Gloom",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: "Vileplume",
    evolution_requirement: { stone: "Leaf Stone" },
    evolution_relation: { chain: "Oddish -> Gloom -> Vileplume" },
    size: "small",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 45,
    name: "Vileplume",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Oddish -> Gloom -> Vileplume" },
    size: "medium",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 46,
    name: "Paras",
    type: ["Bug", "Grass"],
    counter_type: ["Fire", "Flying", "Ice", "Poison", "Rock"],
    evolution: "Parasect",
    evolution_requirement: { level: 24 },
    evolution_relation: { chain: "Paras -> Parasect" },
    size: "extra_small",
    egg_group: ["Grass", "Bug"],
    legendary: false,
  },
  {
    id: 47,
    name: "Parasect",
    type: ["Bug", "Grass"],
    counter_type: ["Fire", "Flying", "Ice", "Poison", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Paras -> Parasect" },
    size: "medium",
    egg_group: ["Grass", "Bug"],
    legendary: false,
  },
  {
    id: 48,
    name: "Venonat",
    type: ["Bug", "Poison"],
    counter_type: ["Fire", "Flying", "Psychic", "Rock"],
    evolution: "Venomoth",
    evolution_requirement: { level: 31 },
    evolution_relation: { chain: "Venonat -> Venomoth" },
    size: "medium",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 49,
    name: "Venomoth",
    type: ["Bug", "Poison"],
    counter_type: ["Fire", "Flying", "Psychic", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Venonat -> Venomoth" },
    size: "medium",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 50,
    name: "Diglett",
    type: ["Ground"],
    counter_type: ["Grass", "Ice", "Water"],
    evolution: "Dugtrio",
    evolution_requirement: { level: 26 },
    evolution_relation: { chain: "Diglett -> Dugtrio" },
    size: "extra_small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 51,
    name: "Dugtrio",
    type: ["Ground"],
    counter_type: ["Grass", "Ice", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Diglett -> Dugtrio" },
    size: "small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 52,
    name: "Meowth",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: "Persian",
    evolution_requirement: { level: 28 },
    evolution_relation: { chain: "Meowth -> Persian" },
    size: "extra_small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 53,
    name: "Persian",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Meowth -> Persian" },
    size: "medium",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 54,
    name: "Psyduck",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Golduck",
    evolution_requirement: { level: 33 },
    evolution_relation: { chain: "Psyduck -> Golduck" },
    size: "small",
    egg_group: ["Water 1", "Field"],
    legendary: false,
  },
  {
    id: 55,
    name: "Golduck",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Psyduck -> Golduck" },
    size: "medium",
    egg_group: ["Water 1", "Field"],
    legendary: false,
  },
  {
    id: 56,
    name: "Mankey",
    type: ["Fighting"],
    counter_type: ["Fairy", "Flying", "Psychic"],
    evolution: "Primeape",
    evolution_requirement: { level: 28 },
    evolution_relation: { chain: "Mankey -> Primeape" },
    size: "small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 57,
    name: "Primeape",
    type: ["Fighting"],
    counter_type: ["Fairy", "Flying", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Mankey -> Primeape" },
    size: "medium",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 58,
    name: "Growlithe",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: "Arcanine",
    evolution_requirement: { stone: "Fire Stone" },
    evolution_relation: { chain: "Growlithe -> Arcanine" },
    size: "small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 59,
    name: "Arcanine",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Growlithe -> Arcanine" },
    size: "large",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 60,
    name: "Poliwag",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Poliwhirl",
    evolution_requirement: { level: 25 },
    evolution_relation: { chain: "Poliwag -> Poliwhirl -> Poliwrath" },
    size: "small",
    egg_group: ["Water 1"],
    legendary: false,
  },
  {
    id: 61,
    name: "Poliwhirl",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Poliwrath",
    evolution_requirement: { stone: "Water Stone" },
    evolution_relation: { chain: "Poliwag -> Poliwhirl -> Poliwrath" },
    size: "medium",
    egg_group: ["Water 1"],
    legendary: false,
  },
  {
    id: 62,
    name: "Poliwrath",
    type: ["Water", "Fighting"],
    counter_type: ["Electric", "Fairy", "Flying", "Grass", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Poliwag -> Poliwhirl -> Poliwrath" },
    size: "medium",
    egg_group: ["Water 1"],
    legendary: false,
  },
  {
    id: 63,
    name: "Abra",
    type: ["Psychic"],
    counter_type: ["Bug", "Dark", "Ghost"],
    evolution: "Kadabra",
    evolution_requirement: { level: 16 },
    evolution_relation: { chain: "Abra -> Kadabra -> Alakazam" },
    size: "small",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 64,
    name: "Kadabra",
    type: ["Psychic"],
    counter_type: ["Bug", "Dark", "Ghost"],
    evolution: "Alakazam",
    evolution_requirement: { condition: "Trade" },
    evolution_relation: { chain: "Abra -> Kadabra -> Alakazam" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 65,
    name: "Alakazam",
    type: ["Psychic"],
    counter_type: ["Bug", "Dark", "Ghost"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Abra -> Kadabra -> Alakazam" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 66,
    name: "Machop",
    type: ["Fighting"],
    counter_type: ["Fairy", "Flying", "Psychic"],
    evolution: "Machoke",
    evolution_requirement: { level: 28 },
    evolution_relation: { chain: "Machop -> Machoke -> Machamp" },
    size: "small",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 67,
    name: "Machoke",
    type: ["Fighting"],
    counter_type: ["Fairy", "Flying", "Psychic"],
    evolution: "Machamp",
    evolution_requirement: { condition: "Trade" },
    evolution_relation: { chain: "Machop -> Machoke -> Machamp" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 68,
    name: "Machamp",
    type: ["Fighting"],
    counter_type: ["Fairy", "Flying", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Machop -> Machoke -> Machamp" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 69,
    name: "Bellsprout",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: "Weepinbell",
    evolution_requirement: { level: 21 },
    evolution_relation: { chain: "Bellsprout -> Weepinbell -> Victreebel" },
    size: "small",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 70,
    name: "Weepinbell",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: "Victreebel",
    evolution_requirement: { stone: "Leaf Stone" },
    evolution_relation: { chain: "Bellsprout -> Weepinbell -> Victreebel" },
    size: "medium",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 71,
    name: "Victreebel",
    type: ["Grass", "Poison"],
    counter_type: ["Fire", "Flying", "Ice", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Bellsprout -> Weepinbell -> Victreebel" },
    size: "medium",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 72,
    name: "Tentacool",
    type: ["Water", "Poison"],
    counter_type: ["Electric", "Ground", "Psychic"],
    evolution: "Tentacruel",
    evolution_requirement: { level: 30 },
    evolution_relation: { chain: "Tentacool -> Tentacruel" },
    size: "small",
    egg_group: ["Water 3"],
    legendary: false,
  },
  {
    id: 73,
    name: "Tentacruel",
    type: ["Water", "Poison"],
    counter_type: ["Electric", "Ground", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Tentacool -> Tentacruel" },
    size: "medium",
    egg_group: ["Water 3"],
    legendary: false,
  },
  {
    id: 74,
    name: "Geodude",
    type: ["Rock", "Ground"],
    counter_type: ["Fighting", "Grass", "Ground", "Ice", "Steel", "Water"],
    evolution: "Graveler",
    evolution_requirement: { level: 25 },
    evolution_relation: { chain: "Geodude -> Graveler -> Golem" },
    size: "extra_small",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 75,
    name: "Graveler",
    type: ["Rock", "Ground"],
    counter_type: ["Fighting", "Grass", "Ground", "Ice", "Steel", "Water"],
    evolution: "Golem",
    evolution_requirement: { condition: "Trade" },
    evolution_relation: { chain: "Geodude -> Graveler -> Golem" },
    size: "medium",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 76,
    name: "Golem",
    type: ["Rock", "Ground"],
    counter_type: ["Fighting", "Grass", "Ground", "Ice", "Steel", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Geodude -> Graveler -> Golem" },
    size: "medium",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 77,
    name: "Ponyta",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: "Rapidash",
    evolution_requirement: { level: 40 },
    evolution_relation: { chain: "Ponyta -> Rapidash" },
    size: "medium",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 78,
    name: "Rapidash",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Ponyta -> Rapidash" },
    size: "medium",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 79,
    name: "Slowpoke",
    type: ["Water", "Psychic"],
    counter_type: ["Bug", "Dark", "Electric", "Ghost", "Grass"],
    evolution: "Slowbro",
    evolution_requirement: { level: 37 },
    evolution_relation: { chain: "Slowpoke -> Slowbro" },
    size: "medium",
    egg_group: ["Monster", "Water 1"],
    legendary: false,
  },
  {
    id: 80,
    name: "Slowbro",
    type: ["Water", "Psychic"],
    counter_type: ["Bug", "Dark", "Electric", "Ghost", "Grass"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Slowpoke -> Slowbro" },
    size: "medium",
    egg_group: ["Monster", "Water 1"],
    legendary: false,
  },
  {
    id: 81,
    name: "Magnemite",
    type: ["Electric", "Steel"],
    counter_type: ["Fighting", "Fire", "Ground"],
    evolution: "Magneton",
    evolution_requirement: { level: 30 },
    evolution_relation: { chain: "Magnemite -> Magneton" },
    size: "extra_small",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 82,
    name: "Magneton",
    type: ["Electric", "Steel"],
    counter_type: ["Fighting", "Fire", "Ground"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Magnemite -> Magneton" },
    size: "medium",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 83,
    name: "Farfetch'd",
    type: ["Normal", "Flying"],
    counter_type: ["Electric", "Ice", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Farfetch'd" },
    size: "small",
    egg_group: ["Flying", "Field"],
    legendary: false,
  },
  {
    id: 84,
    name: "Doduo",
    type: ["Normal", "Flying"],
    counter_type: ["Electric", "Ice", "Rock"],
    evolution: "Dodrio",
    evolution_requirement: { level: 31 },
    evolution_relation: { chain: "Doduo -> Dodrio" },
    size: "medium",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 85,
    name: "Dodrio",
    type: ["Normal", "Flying"],
    counter_type: ["Electric", "Ice", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Doduo -> Dodrio" },
    size: "medium",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 86,
    name: "Seel",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Dewgong",
    evolution_requirement: { level: 34 },
    evolution_relation: { chain: "Seel -> Dewgong" },
    size: "medium",
    egg_group: ["Water 1", "Field"],
    legendary: false,
  },
  {
    id: 87,
    name: "Dewgong",
    type: ["Water", "Ice"],
    counter_type: ["Electric", "Fighting", "Grass", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Seel -> Dewgong" },
    size: "medium",
    egg_group: ["Water 1", "Field"],
    legendary: false,
  },
  {
    id: 88,
    name: "Grimer",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: "Muk",
    evolution_requirement: { level: 38 },
    evolution_relation: { chain: "Grimer -> Muk" },
    size: "small",
    egg_group: ["Amorphous"],
    legendary: false,
  },
  {
    id: 89,
    name: "Muk",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Grimer -> Muk" },
    size: "medium",
    egg_group: ["Amorphous"],
    legendary: false,
  },
  {
    id: 90,
    name: "Shellder",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Cloyster",
    evolution_requirement: { stone: "Water Stone" },
    evolution_relation: { chain: "Shellder -> Cloyster" },
    size: "extra_small",
    egg_group: ["Water 3"],
    legendary: false,
  },
  {
    id: 91,
    name: "Cloyster",
    type: ["Water", "Ice"],
    counter_type: ["Electric", "Fighting", "Grass", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Shellder -> Cloyster" },
    size: "medium",
    egg_group: ["Water 3"],
    legendary: false,
  },
  {
    id: 92,
    name: "Gastly",
    type: ["Ghost", "Poison"],
    counter_type: ["Dark", "Ghost", "Ground", "Psychic"],
    evolution: "Haunter",
    evolution_requirement: { level: 25 },
    evolution_relation: { chain: "Gastly -> Haunter -> Gengar" },
    size: "medium",
    egg_group: ["Amorphous"],
    legendary: false,
  },
  {
    id: 93,
    name: "Haunter",
    type: ["Ghost", "Poison"],
    counter_type: ["Dark", "Ghost", "Ground", "Psychic"],
    evolution: "Gengar",
    evolution_requirement: { condition: "Trade" },
    evolution_relation: { chain: "Gastly -> Haunter -> Gengar" },
    size: "medium",
    egg_group: ["Amorphous"],
    legendary: false,
  },
  {
    id: 94,
    name: "Gengar",
    type: ["Ghost", "Poison"],
    counter_type: ["Dark", "Ghost", "Ground", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Gastly -> Haunter -> Gengar" },
    size: "medium",
    egg_group: ["Amorphous"],
    legendary: false,
  },
  {
    id: 95,
    name: "Onix",
    type: ["Rock", "Ground"],
    counter_type: ["Fighting", "Grass", "Ground", "Ice", "Steel", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Onix" },
    size: "mega_large",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 96,
    name: "Drowzee",
    type: ["Psychic"],
    counter_type: ["Bug", "Dark", "Ghost"],
    evolution: "Hypno",
    evolution_requirement: { level: 26 },
    evolution_relation: { chain: "Drowzee -> Hypno" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 97,
    name: "Hypno",
    type: ["Psychic"],
    counter_type: ["Bug", "Dark", "Ghost"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Drowzee -> Hypno" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 98,
    name: "Krabby",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Kingler",
    evolution_requirement: { level: 28 },
    evolution_relation: { chain: "Krabby -> Kingler" },
    size: "extra_small",
    egg_group: ["Water 3"],
    legendary: false,
  },
  {
    id: 99,
    name: "Kingler",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Krabby -> Kingler" },
    size: "medium",
    egg_group: ["Water 3"],
    legendary: false,
  },
  {
    id: 100,
    name: "Voltorb",
    type: ["Electric"],
    counter_type: ["Ground"],
    evolution: "Electrode",
    evolution_requirement: { level: 30 },
    evolution_relation: { chain: "Voltorb -> Electrode" },
    size: "small",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 101,
    name: "Electrode",
    type: ["Electric"],
    counter_type: ["Ground"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Voltorb -> Electrode" },
    size: "medium",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 102,
    name: "Exeggcute",
    type: ["Grass", "Psychic"],
    counter_type: ["Bug", "Dark", "Fire", "Flying", "Ghost", "Ice", "Poison"],
    evolution: "Exeggutor",
    evolution_requirement: { stone: "Leaf Stone" },
    evolution_relation: { chain: "Exeggcute -> Exeggutor" },
    size: "extra_small",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 103,
    name: "Exeggutor",
    type: ["Grass", "Psychic"],
    counter_type: ["Bug", "Dark", "Fire", "Flying", "Ghost", "Ice", "Poison"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Exeggcute -> Exeggutor" },
    size: "large",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 104,
    name: "Cubone",
    type: ["Ground"],
    counter_type: ["Grass", "Ice", "Water"],
    evolution: "Marowak",
    evolution_requirement: { level: 28 },
    evolution_relation: { chain: "Cubone -> Marowak" },
    size: "extra_small",
    egg_group: ["Monster"],
    legendary: false,
  },
  {
    id: 105,
    name: "Marowak",
    type: ["Ground"],
    counter_type: ["Grass", "Ice", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Cubone -> Marowak" },
    size: "medium",
    egg_group: ["Monster"],
    legendary: false,
  },
  {
    id: 106,
    name: "Hitmonlee",
    type: ["Fighting"],
    counter_type: ["Fairy", "Flying", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Hitmonlee" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 107,
    name: "Hitmonchan",
    type: ["Fighting"],
    counter_type: ["Fairy", "Flying", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Hitmonchan" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 108,
    name: "Lickitung",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Lickitung" },
    size: "medium",
    egg_group: ["Monster"],
    legendary: false,
  },
  {
    id: 109,
    name: "Koffing",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: "Weezing",
    evolution_requirement: { level: 35 },
    evolution_relation: { chain: "Koffing -> Weezing" },
    size: "small",
    egg_group: ["Amorphous"],
    legendary: false,
  },
  {
    id: 110,
    name: "Weezing",
    type: ["Poison"],
    counter_type: ["Ground", "Psychic"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Koffing -> Weezing" },
    size: "medium",
    egg_group: ["Amorphous"],
    legendary: false,
  },
  {
    id: 111,
    name: "Rhyhorn",
    type: ["Ground", "Rock"],
    counter_type: ["Fighting", "Grass", "Ground", "Ice", "Steel", "Water"],
    evolution: "Rhydon",
    evolution_requirement: { level: 42 },
    evolution_relation: { chain: "Rhyhorn -> Rhydon" },
    size: "medium",
    egg_group: ["Field", "Monster"],
    legendary: false,
  },
  {
    id: 112,
    name: "Rhydon",
    type: ["Ground", "Rock"],
    counter_type: ["Fighting", "Grass", "Ground", "Ice", "Steel", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Rhyhorn -> Rhydon" },
    size: "large",
    egg_group: ["Field", "Monster"],
    legendary: false,
  },
  {
    id: 113,
    name: "Chansey",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Chansey" },
    size: "medium",
    egg_group: ["Fairy"],
    legendary: false,
  },
  {
    id: 114,
    name: "Tangela",
    type: ["Grass"],
    counter_type: ["Bug", "Fire", "Flying", "Ice", "Poison"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Tangela" },
    size: "medium",
    egg_group: ["Grass"],
    legendary: false,
  },
  {
    id: 115,
    name: "Kangaskhan",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Kangaskhan" },
    size: "large",
    egg_group: ["Monster"],
    legendary: false,
  },
  {
    id: 116,
    name: "Horsea",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Seadra",
    evolution_requirement: { level: 32 },
    evolution_relation: { chain: "Horsea -> Seadra" },
    size: "extra_small",
    egg_group: ["Water 1", "Dragon"],
    legendary: false,
  },
  {
    id: 117,
    name: "Seadra",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Horsea -> Seadra" },
    size: "medium",
    egg_group: ["Water 1", "Dragon"],
    legendary: false,
  },
  {
    id: 118,
    name: "Goldeen",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Seaking",
    evolution_requirement: { level: 33 },
    evolution_relation: { chain: "Goldeen -> Seaking" },
    size: "small",
    egg_group: ["Water 2"],
    legendary: false,
  },
  {
    id: 119,
    name: "Seaking",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Goldeen -> Seaking" },
    size: "medium",
    egg_group: ["Water 2"],
    legendary: false,
  },
  {
    id: 120,
    name: "Staryu",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Starmie",
    evolution_requirement: { stone: "Water Stone" },
    evolution_relation: { chain: "Staryu -> Starmie" },
    size: "medium",
    egg_group: ["Water 3"],
    legendary: false,
  },
  {
    id: 121,
    name: "Starmie",
    type: ["Water", "Psychic"],
    counter_type: ["Bug", "Dark", "Electric", "Ghost", "Grass"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Staryu -> Starmie" },
    size: "medium",
    egg_group: ["Water 3"],
    legendary: false,
  },
  {
    id: 122,
    name: "Mr. Mime",
    type: ["Psychic", "Fairy"],
    counter_type: ["Ghost", "Poison", "Steel"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Mr. Mime" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 123,
    name: "Scyther",
    type: ["Bug", "Flying"],
    counter_type: ["Electric", "Fire", "Flying", "Ice", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Scyther" },
    size: "medium",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 124,
    name: "Jynx",
    type: ["Ice", "Psychic"],
    counter_type: ["Dark", "Fire", "Ghost", "Rock", "Steel"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Jynx" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 125,
    name: "Electabuzz",
    type: ["Electric"],
    counter_type: ["Ground"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Electabuzz" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 126,
    name: "Magmar",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Magmar" },
    size: "medium",
    egg_group: ["Human-Like"],
    legendary: false,
  },
  {
    id: 127,
    name: "Pinsir",
    type: ["Bug"],
    counter_type: ["Fire", "Flying", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Pinsir" },
    size: "medium",
    egg_group: ["Bug"],
    legendary: false,
  },
  {
    id: 128,
    name: "Tauros",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Tauros" },
    size: "medium",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 129,
    name: "Magikarp",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: "Gyarados",
    evolution_requirement: { level: 20 },
    evolution_relation: { chain: "Magikarp -> Gyarados" },
    size: "small",
    egg_group: ["Water 2", "Dragon"],
    legendary: false,
  },
  {
    id: 130,
    name: "Gyarados",
    type: ["Water", "Flying"],
    counter_type: ["Electric", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Magikarp -> Gyarados" },
    size: "extra_large",
    egg_group: ["Water 2", "Dragon"],
    legendary: false,
  },
  {
    id: 131,
    name: "Lapras",
    type: ["Water", "Ice"],
    counter_type: ["Electric", "Fighting", "Grass", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Lapras" },
    size: "large",
    egg_group: ["Monster", "Water 1"],
    legendary: false,
  },
  {
    id: 132,
    name: "Ditto",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Ditto" },
    size: "extra_small",
    egg_group: ["Ditto"],
    legendary: false,
  },
  {
    id: 133,
    name: "Eevee",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: ["Vaporeon", "Jolteon", "Flareon"],
    evolution_requirement: { stone: "Water, Thunder or Fire Stone" },
    evolution_relation: { chain: "Eevee -> Vaporeon / Jolteon / Flareon" },
    size: "extra_small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 134,
    name: "Vaporeon",
    type: ["Water"],
    counter_type: ["Electric", "Grass"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Eevee -> Vaporeon / Jolteon / Flareon" },
    size: "medium",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 135,
    name: "Jolteon",
    type: ["Electric"],
    counter_type: ["Ground"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Eevee -> Vaporeon / Jolteon / Flareon" },
    size: "small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 136,
    name: "Flareon",
    type: ["Fire"],
    counter_type: ["Ground", "Rock", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Eevee -> Vaporeon / Jolteon / Flareon" },
    size: "small",
    egg_group: ["Field"],
    legendary: false,
  },
  {
    id: 137,
    name: "Porygon",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Porygon" },
    size: "small",
    egg_group: ["Mineral"],
    legendary: false,
  },
  {
    id: 138,
    name: "Omanyte",
    type: ["Rock", "Water"],
    counter_type: ["Electric", "Fighting", "Grass", "Ground"],
    evolution: "Omastar",
    evolution_requirement: { level: 40 },
    evolution_relation: { chain: "Omanyte -> Omastar" },
    size: "extra_small",
    egg_group: ["Water 3", "Water 1"],
    legendary: false,
  },
  {
    id: 139,
    name: "Omastar",
    type: ["Rock", "Water"],
    counter_type: ["Electric", "Fighting", "Grass", "Ground"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Omanyte -> Omastar" },
    size: "medium",
    egg_group: ["Water 3", "Water 1"],
    legendary: false,
  },
  {
    id: 140,
    name: "Kabuto",
    type: ["Rock", "Water"],
    counter_type: ["Electric", "Fighting", "Grass", "Ground"],
    evolution: "Kabutops",
    evolution_requirement: { level: 40 },
    evolution_relation: { chain: "Kabuto -> Kabutops" },
    size: "small",
    egg_group: ["Water 3", "Water 1"],
    legendary: false,
  },
  {
    id: 141,
    name: "Kabutops",
    type: ["Rock", "Water"],
    counter_type: ["Electric", "Fighting", "Grass", "Ground"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Kabuto -> Kabutops" },
    size: "medium",
    egg_group: ["Water 3", "Water 1"],
    legendary: false,
  },
  {
    id: 142,
    name: "Aerodactyl",
    type: ["Rock", "Flying"],
    counter_type: ["Electric", "Ice", "Rock", "Steel", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Aerodactyl" },
    size: "medium",
    egg_group: ["Flying"],
    legendary: false,
  },
  {
    id: 143,
    name: "Snorlax",
    type: ["Normal"],
    counter_type: ["Fighting"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Snorlax" },
    size: "large",
    egg_group: ["Monster"],
    legendary: false,
  },
  {
    id: 144,
    name: "Articuno",
    type: ["Ice", "Flying"],
    counter_type: ["Electric", "Fire", "Rock", "Steel"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Articuno" },
    size: "medium",
    egg_group: ["Undiscovered"],
    legendary: true,
  },
  {
    id: 145,
    name: "Zapdos",
    type: ["Electric", "Flying"],
    counter_type: ["Ice", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Zapdos" },
    size: "medium",
    egg_group: ["Undiscovered"],
    legendary: true,
  },
  {
    id: 146,
    name: "Moltres",
    type: ["Fire", "Flying"],
    counter_type: ["Electric", "Rock", "Water"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Moltres" },
    size: "large",
    egg_group: ["Undiscovered"],
    legendary: true,
  },
  {
    id: 147,
    name: "Dratini",
    type: ["Dragon"],
    counter_type: ["Dragon", "Fairy", "Ice"],
    evolution: "Dragonair",
    evolution_requirement: { level: 30 },
    evolution_relation: { chain: "Dratini -> Dragonair -> Dragonite" },
    size: "medium",
    egg_group: ["Water 1", "Dragon"],
    legendary: false,
  },
  {
    id: 148,
    name: "Dragonair",
    type: ["Dragon"],
    counter_type: ["Dragon", "Fairy", "Ice"],
    evolution: "Dragonite",
    evolution_requirement: { level: 55 },
    evolution_relation: { chain: "Dratini -> Dragonair -> Dragonite" },
    size: "large",
    egg_group: ["Water 1", "Dragon"],
    legendary: false,
  },
  {
    id: 149,
    name: "Dragonite",
    type: ["Dragon", "Flying"],
    counter_type: ["Dragon", "Fairy", "Ice", "Rock"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Dratini -> Dragonair -> Dragonite" },
    size: "large",
    egg_group: ["Water 1", "Dragon"],
    legendary: false,
  },
  {
    id: 150,
    name: "Mewtwo",
    type: ["Psychic"],
    counter_type: ["Bug", "Dark", "Ghost"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Mewtwo" },
    size: "large",
    egg_group: ["Undiscovered"],
    legendary: true,
  },
  {
    id: 151,
    name: "Mew",
    type: ["Psychic"],
    counter_type: ["Bug", "Dark", "Ghost"],
    evolution: null,
    evolution_requirement: null,
    evolution_relation: { chain: "Mew" },
    size: "extra_small",
    egg_group: ["Undiscovered"],
    legendary: true,
  },
];

module.exports = pokemonData; // Export the pokemonData array
